# Contains JavaScript prototypes for Python.
# Author: Evan Cassidy
# Date: 4/1/2026

class console:
    def log(*args) -> None: ...

class window:
    def setTimeout(*args) -> object: ...
    def setInterval(*args) -> object: ...

class document:
    def getElementById(*args) -> object: ...
    def getElementsByClassName(*args) -> object: ...
    def getElementsByTagName(*args) -> object: ...